- Cargo.toml
- src/fs/file_io_ext.rs
- src/io/is_terminal.rs
- tests/allocate.rs
- tests/is_terminal.rs
Update to posish 0.6.0 and add an `allocate` function to `FileIoExt` using `posix_fallocate` where available.
> Add an `allocate` function to `FileIoExt`.

- src/fs/file_io_ext.rs
The presence of the chain method means we cannot use FileIoExt as a trait object.
Remove chain, and add a "test" that FileIoExt can be used as a trait
object.
> FileIoExt: remove chain method

- src/fs/file_io_ext.rs
- src/fs/mod.rs
these methods return generic structs which are parameterized to a
concrete `std::fs::File`. For any implementation of this trait thats not
backed by a File, this may be impossible to satisify.
> FileIoExt: remove `bytes` and `take` methods

- Cargo.toml
- build.rs
- src/fs/file_io_ext.rs
- src/fs/mod.rs
- src/io/mod.rs
- src/io/peek.rs
- src/io/read_ready.rs
- src/lib.rs
- tests/live_rename.rs
- tests/peek.rs
- tests/vectored_at.rs
Add a `peek` function to `FileIoExt`, a `Peek` trait, and implementations for `PipeReader`, `CharDevice`, and `SocketpairStream`.
> Add Peek and implement ReadReady and Peek for more types

- Cargo.toml
- src/fs/fd_flags.rs
- src/fs/mod.rs
- tests/fd_flags.rs
This provides the `get_fd_flags` and `set_fd_flags` operations, which on
Posix-ish platforms are wrappers around `fcntl` with `F_GETFL` and `F_SETFL`.
> Add a `GetSetFdFlags` extension trait.

- src/fs/file_io_ext.rs
- tests/allocate.rs
Wasi tests showed that this was truncating the file!
We don't believe that it is possible to implement this faithfully on Windows without exposing a race condition. So, refuse to implement it at all.
> FileIoExt: make `allocate` just return an error on windows

- src/fs/file_io_ext.rs
With unsafe-io's AsUnsafeFile's new features, it's now possible to
implement FileIoExt for Windows too.
> Implement FileIoExt for all AsUnsafeFile impls on Windows too.

- Cargo.toml
This is the same version used by other cap- crates, and results in fewer
different versions when embedded by final users.
> Upgrade winx to version 0.25

- Cargo.toml
- src/fs/file_io_ext.rs
- tests/allocate.rs
This is very similar to bytecodealliance/posish#12, in that it basically adds configuration pragmas to avoid using unsupported features on OpenBSD.
The `Cargo.toml` file in this branch currently includes a patch to refer to a modified `posish`; when the PR above is merged and a new version of `posish` is on crates.io, then I can update this PR to refer to it. Thanks!
> Support OpenBSD.

- .github/workflows/main.yml
- Cargo.toml
- src/fs/fd_flags.rs
- src/fs/file_io_ext.rs
- src/fs/mod.rs
- src/io/is_read_write.rs
- src/io/is_terminal.rs
- src/io/peek.rs
- src/io/read_ready.rs
- tests/fd_flags.rs
- tests/sys_common/io.rs
This switches from unsafe-io and `UnsafeHandle` to io-lifetimes and
`AsFilelike`, which overall is safer and simpler.
However, this does require splitting `GetSetFdFlags::set_fd_flags` into
two steps, to allow the first step to create lifetimes which the compiler
can be sure end before the second step.
> Update to the latest posish, cap-std, and io-lifetimes.

- Cargo.toml
- src/fs/fd_flags.rs
- src/fs/file_io_ext.rs
- src/io/is_read_write.rs
- src/io/is_terminal.rs
- src/io/peek.rs
- src/io/read_ready.rs
This also switches from winapi to windows-sys.
This is mostly straightforward; most of the changes are due to
`as_filelike_view` returning a view that no longer implements `DerefMut`.
> Update to rustix 0.35.6 and cap-std 0.25.

- .github/workflows/main.yml
- src/fs/file_io_ext.rs
- tests/vectored_at.rs
Teach `read_exact_vectored` and `read_exact_vectored_at` to recognize
when the stream ends before the requested buffers are full, and to
return an `UnexpectedEOF` error in that case.
> Handle unexpected EOF in `read_exact_vectored` and `read_exact_vectored_at`.

- Cargo.toml
- src/fs/file_io_ext.rs
- src/io/io_ext.rs
- src/io/is_read_write.rs
- src/io/is_terminal.rs
- src/io/mod.rs
- src/io/peek.rs
- src/io/read_ready.rs
- tests/live_rename.rs
- tests/read_to_end.rs
- tests/vectored_at.rs
Leave file-specific functions such as `*_at` functions in `FileIoExt`,
and split out all the non-file-specific things into a new `IoExt` trait.
> Split an `IoExt` out of `FileIoExt`.

- src/io/read_ready.rs
Implement `ReadReady` for `&[u8]`, `Cursor`, `BufReader`, `Chain`, and other `Read` implementors.
> Implement `ReadReady` for more `std::io::Read` implementors.

- Cargo.toml
- src/fs/file_io_ext.rs
Add functions to append to a file to `FileIoExt`. This is implemented using `pwritev2` with `RWF_APPEND` on Linux, and `F_SETFL`+`O_APPEND` on other Unix platforms.
`F_SETFL`+`O_APPEND` is not atomic with respect to other users of the file description; this is a documented limitation.
> Add an `append` API to `FileIoExt`.

- Cargo.toml
- src/fs/file_io_ext.rs
- tests/vectored_at.rs
On Windows, writing or seeking past the end of the file extends the file with uninitialized bytes. In order to support POSIX-compatible behavior, teach `write_at` to fill those bytes with zeros.
> Make `write_at` etc. on Windows fill with zeros.

- .github/workflows/main.yml
- src/fs/fd_flags.rs
- src/fs/file_io_ext.rs
- tests/fd_flags.rs
Don't fail on Windows if `O_NONBLOCK` is set; Unix doesn't usually implement nonblocking behavior for regular files either, so it's ok to just ignore.
Don't set `FILE_FLAG_WRITE_THROUGH` if only `RSYNC` is requested since `O_RSYNC` is defined by POSIX to request the level of integrity requested by the `O_SYNC` and `O_DSYNC` flags.
And don't report that Windows supports `O_SYNC`; my reading of `FILE_FLAG_WRITE_THROUGH` is that it's more like `O_DSYNC` than `O_SYNC`.
> Adjust `O_NONBLOCK`, `O_SYNC`, `O_RSYNC` behavior on Windows.

- Cargo.toml
- src/fs/file_io_ext.rs
Update to rustix 0.37. The only code change here is to switch from std::io::SeekFrom to rustix::io::SeekFrom.
> Update to rustix 0.37.

- src/fs/mod.rs
- src/io/read_ready.rs
- tests/read_ready.rs
`File` can open special devices like /dev/random or /dev/null; make sure those are handled properly in `ReadReady`.
Also, correctly report the number of ready bytes if the current position is in the middle of a file.
> Handle non-files in the the `ReadRead` implementation for `std::fs::File`.

- src/fs/file_io_ext.rs
- tests/vectored_at.rs
This commit it borne out of CI failures on bytecodealliance/wasmtime#7638. Investigating this failure has revealed a number of aspects here which I've attempted to address in this PR. The notable changes here are:
* The current code in this crate was handling the case where `FileExt::seek_write` on Windows was leaving intermediate bytes as undefined when a write happened beyond the end of a file. I believe that this is due to an error in the documentation of the Rust standard library which I've submitted rust-lang/rust#120452 to fix.
* Removing handling of "always write zeros" handles the primary failure of the PR bytecodealliance/wasmtime#7638 which is that `write_vectored_at` was always returning 0 on Windows for writes past the end of the file. This is because Windows doesn't have a …
> Simplify some filesystem extensions on Windows

- build.rs
io-lifetimes and rustix and a few other crates I maintain have similar build.rs scripts. Port some of the changes from rustix here to keep them in sync.
> Sync with rustix' build.rs changes (#58)
